---
- name: Install desktop apps via Homebrew casks
  community.general.homebrew_cask:
    name: "{{ apps_cask_packages_darwin }}"
    state: present
  tags:
    - apps

- name: Import terminal emulator installs
  ansible.builtin.import_tasks: terminals-darwin.yml
  tags:
    - apps
