---
- name: Install desktop apps via apt
  ansible.builtin.apt:
    name: >-
      {{ apps_apt_packages_debian
         + (['brave-browser', '1password', 'spotify-client'] if ansible_facts['architecture'] == 'x86_64' else [])
         + ['tailscale', 'librewolf'] }}
    state: present
    update_cache: true
  become: true
  tags:
    - apps
