---
- name: Configure SSH hardening
  ansible.builtin.import_tasks: ssh.yml
  tags:
    - security
    - ssh

- name: Configure firewall (Linux)
  ansible.builtin.import_tasks: firewall.yml
  when: ansible_os_family == "Debian"
  tags:
    - security
    - firewall

- name: Configure fail2ban (Linux)
  ansible.builtin.import_tasks: fail2ban.yml
  when: ansible_os_family == "Debian"
  tags:
    - security
    - fail2ban
