---
galaxy_info:
  description: Install desktop applications and external apt repositories
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions: [all]
    - name: Debian
      versions: [all]
    - name: MacOSX
      versions: [all]
dependencies: []
