---
- name: Install Docker (Debian/Ubuntu)
  ansible.builtin.import_tasks: docker-debian.yml
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - docker

- name: Install Docker (macOS)
  ansible.builtin.import_tasks: docker-darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - docker
