---
- name: Validate sshd configuration
  ansible.builtin.command: sshd -t
  changed_when: false
  become: true
  listen: restart sshd

- name: Restart sshd service
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    enabled: true
  become: true
  listen: restart sshd

- name: Validate sshd configuration (macOS)
  ansible.builtin.command: sshd -t
  changed_when: false
  become: true
  listen: restart sshd macos

- name: Restart sshd service (macOS)
  ansible.builtin.command:
    cmd: launchctl kickstart -k system/com.openssh.sshd
  become: true
  listen: restart sshd macos

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true
  become: true

- name: reload ufw
  community.general.ufw:
    state: reloaded
  become: true
