---
galaxy_info:
  description: Install fnm (Fast Node Manager) and Node.js versions
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions: [all]
    - name: Debian
      versions: [all]
    - name: MacOSX
      versions: [all]
dependencies: []
